# Generated by Django 4.2.8 on 2023-12-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="description",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="severity_level",
        ),
        migrations.AddField(
            model_name="complaint",
            name="complaint_type",
            field=models.CharField(
                choices=[
                    ("dresscode", "Improper dresscode"),
                    ("informal_shoe", "Informal shoe"),
                    ("hairstyle", "Improper hairstyle"),
                    ("untrimmed_beard", "Untrimmed beard"),
                    ("socks_unworn", "Socks unworn"),
                    ("shoe_unworn", "Shoe unworn"),
                    ("blazer_unworn", "Blazer unworn"),
                ],
                default="dresscode",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
