# Generated by Django 4.2.8 on 2023-12-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0002_remove_complaint_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="complaint_type",
            field=models.CharField(
                choices=[
                    ("dresscode", "Improper dress code"),
                    ("informal_shoe", "Informal shoe"),
                    ("hairstyle", "Improper hairstyle"),
                    ("untrimmed_beard", "Untrimmed beard"),
                    ("socks_not_worn", "Socks not worn"),
                    ("shoes_not_worn", "Shoes not worn"),
                    ("blazer_not_worn", "Blazer not worn"),
                ],
                max_length=20,
            ),
        ),
    ]
