# Generated by Django 4.2.8 on 2024-01-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0007_alter_complaint_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="department",
            field=models.CharField(
                choices=[
                    (
                        "B.E.",
                        [
                            ("B.E_BME", "B.E. Bio-Medical Engineering"),
                            ("B.E_CSE", "B.E. Computer Science and Engineering"),
                            ("B.E_CSE_B", "B.E. Computer Science and Engineering (RL)"),
                            (
                                "B.E_ECE",
                                "B.E. Electronics and Communication Engineering",
                            ),
                            ("B.E_MECH", "B.E. Mechanical Engineering"),
                        ],
                    ),
                    (
                        "B.Tech.",
                        [
                            ("BTECH_AE", "B.Tech. Agricultural Engineering"),
                            (
                                "BTECH_AI&DS",
                                "B.Tech. Artificial Intelligence and Data Science",
                            ),
                            ("BTECH_BT", "B.Tech. Bio-Technology"),
                            ("BTECH_IT", "B.Tech. Information Technology"),
                        ],
                    ),
                    (
                        "B.Sc.",
                        [
                            ("BSC_IT", "B.Sc. Information Technology"),
                            ("BSC_CY", "B.Sc. Cyber Security"),
                            (
                                "BSC_AI&DS",
                                "B.Sc. Artificial Intelligence and Data Science",
                            ),
                            ("BSC_CS", "B.Sc. Computer Science"),
                        ],
                    ),
                    (
                        "S&H",
                        [
                            ("S&H_AGRI", "S&H - Agricultural Engineering"),
                            (
                                "S&H_AIML",
                                "S&H - Artificial Intelligence and Machine Learning",
                            ),
                            (
                                "S&H_AI&DS",
                                "S&H - Artificial Intelligence and Data Science",
                            ),
                            ("S&H_BME", "S&H - Bio-Medical Engineering"),
                            ("S&H_BT", "S&H - Biotechnology"),
                            ("S&H_CSE", "S&H - Computer Science and Engineering"),
                            (
                                "S&H_CSE_B",
                                "S&H - Computer Science and Engineering (RL)",
                            ),
                            (
                                "S&H_ECE",
                                "S&H - Electronics and Communication Engineering",
                            ),
                            ("S&H_MECH", "S&H - Mechanical Engineering"),
                            ("S&H_IT", "S&H - Information Technology"),
                        ],
                    ),
                ],
                max_length=20,
            ),
        ),
    ]
